env:
  - GO111MODULE=on

before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
    - go mod download
    - go mod vendor

builds:
  - env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
      - -mod=vendor
    ldflags:
      - -s -w -X "github.com/byDimasik/helm-images/version.Version={{.Version}}" -X "github.com/byDimasik/helm-images/version.Env={{.Env.BUILD_ENVIRONMENT}}" -X "github.com/byDimasik/helm-images/version.BuildDate={{.Date}}" -X "github.com/byDimasik/helm-images/version.Revision={{.Commit}}" -X "github.com/byDimasik/helm-images/version.GoVersion={{.Env.GOVERSION}}" -X "github.com/byDimasik/helm-images/version.Platform={{ .Os }}/{{ .Arch }}"
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    tags:
      - netgo
    binary: '{{ .ProjectName }}'

archives:
  - format: tar.gz
    name_template: >-
      {{- .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    files:
      - plugin.yaml
      - LICENSE
      - completion.yaml
      - install-binary.sh

snapshot:
  name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Runtime.Goos }}_{{ .Runtime.Goarch }}"

checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_SHA256SUMS'
  algorithm: sha256

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

release:
  # release to the public repository
  github:
    owner: byDimasik
    name: helm-images
  name_template: "v{{.Version}}"
