apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-aws
  namespace: default
spec:
  package: xpkg.upbound.io/crossplane-contrib/provider-aws:v0.39.0
---
apiVersion: pkg.crossplane.io/v1
kind: Configuration
metadata:
  name: my-configuration
  namespace: default
spec:
  package: registry.example.com/my-configuration:v1.0.0
---
apiVersion: pkg.crossplane.io/v1
kind: Function
metadata:
  name: function-patch-and-transform
  namespace: default
spec:
  package: xpkg.upbound.io/crossplane-contrib/function-patch-and-transform:v0.1.4
