name: goreleaser

on:
  push:
    tags:
      - "*"

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: Add build vars as env vars for goreleaser
        run: |
          echo "PLUGIN_PATH=$(git rev-parse --show-toplevel)" >> $GITHUB_ENV
          echo "GOVERSION=$(go version | awk '{printf $$3}')" >> $GITHUB_ENV

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: "~> v2"
          args: release --config .goreleaser.yml --clean
        env:
          BUILD_ENVIRONMENT: ${{ github.event.base_ref }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
